#!/usr/bin/env python
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------
# Colifrapy Functional Tests Runner
# -------------------------------------------------------------------
#
#
#   Author : Guillaume PLIQUE
#   Version : 0.1.0
import sys
from colifrapy.tools.colorize import colorize

# Utilities
TESTS = ['logger', 'commander']

def run_test(test):

    # Resetting argv
    sys.argv = [sys.argv[0]]

    # Launching
    print colorize('Running %s functional tests...' % test, 'green')
    print ''
    __import__('tests.%s_functional' % test)

# Running tests
if __name__ == '__main__':
    print colorize(
        '\nColifrapy Functional Tests\n==========================\n',
        'yellow'
    )

    try:
        if sys.argv[1] in TESTS:
            run_test(sys.argv[1])
        else:
            print 'Inexistant test.'
        print ''

    except IndexError:
        for t in TESTS:
            run_test(t)
            print ''
            print '-' * 30
            print ''
